name: build and test C/C++ code

on:
  push:
    branches: [main, dev, 2-add-github-action-ci-for-compiling-test]

  pull_request:
    branches: [main, dev]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure
        run: >
          cmake
          -S .
          -B build
          -DBUILD_UNIT_TEST=ON
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build -C Release --output-on-failure